// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_F-6piYRoxmaca5cLG8R7SlCm5EyPnBs',
    appId: '1:365415055847:web:734cec456e7c104e60fd42',
    messagingSenderId: '365415055847',
    projectId: 'test-yo-panel',
    authDomain: 'test-yo-panel.firebaseapp.com',
    storageBucket: 'test-yo-panel.appspot.com',
    measurementId: 'G-FVRD9YNY3X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1Y1is1W9m1I17Q2J7EDYTo4FUV6emJZk',
    appId: '1:365415055847:android:2f3fa7e757301cdd60fd42',
    messagingSenderId: '365415055847',
    projectId: 'test-yo-panel',
    storageBucket: 'test-yo-panel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCJITvqBOC9ksSZ53pjqcc5nvZ-WpToEUw',
    appId: '1:365415055847:ios:fbf00ec62a896a9760fd42',
    messagingSenderId: '365415055847',
    projectId: 'test-yo-panel',
    storageBucket: 'test-yo-panel.appspot.com',
    iosBundleId: 'com.example.yoPanel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCJITvqBOC9ksSZ53pjqcc5nvZ-WpToEUw',
    appId: '1:365415055847:ios:b64395d70aefa60860fd42',
    messagingSenderId: '365415055847',
    projectId: 'test-yo-panel',
    storageBucket: 'test-yo-panel.appspot.com',
    iosBundleId: 'com.example.yoPanel.RunnerTests',
  );
}
